<?php

namespace lightninghowl\reader;

$d = DIRECTORY_SEPARATOR;
//require_once(realpath(__DIR__ . '/../../../lightninghowl/utils/AutoLoader.class.php'));
$pathToClass = realpath(__DIR__.$d.'..'.$d.'..'.$d.'..'.$d.'lightninghowl'.$d.'reader'.$d.'JsonReader.class.php');
require_once($pathToClass);
    
    //use lightninghowl\reader\JsonReader;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-28 at 09:30:11.
 */
class JsonReaderTest extends \PHPUnit_Framework_TestCase {

    /**
     * @covers lightninghowl\reader\JsonReader::get
     */
    public function testGetA() {
        $d = DIRECTORY_SEPARATOR;
        $rootDir = realpath(__DIR__.$d.'..'.$d.'..'.$d.'..'.$d);
        $jsonPath = $rootDir . $d .'files'. $d .'test'. $d .'test.json';
        
        $object = new JsonReader($jsonPath);
        $this->assertEquals(1, $object->get('status'));
        $this->assertEquals('test', $object->get('message'));
        $this->assertEquals(array('foo' => 'bar'), $object->get('content'));
    }
    
    public function testGetB(){
        $object = new JsonReader('');
        $this->assertEquals(null, $object->get());
        $this->assertEquals(null, $object->get('foo'));
        $this->assertEquals(null, $object->get('bar'));
    }

}
