<?php

namespace lightninghowl\reader;

require_once(__DIR__ . '/../../../lightninghowl/utils/AutoLoader.class.php');;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-28 at 09:30:11.
 */
class JsonReaderTest extends \PHPUnit_Framework_TestCase {

    /**
     * @covers lightninghowl\reader\JsonReader::get
     */
    public function testGetA() {
        $object = new JsonReader('C:\\xampp\\htdocs\\househub\\files\\test\\test.json');
        $this->assertEquals(1, $object->get('status'));
        $this->assertEquals('test', $object->get('message'));
        $this->assertEquals(array('foo' => 'bar'), $object->get('content'));
    }
    
    public function testGetB(){
        $object = new JsonReader('');
        $this->assertEquals(null, $object->get());
        $this->assertEquals(null, $object->get('foo'));
        $this->assertEquals(null, $object->get('bar'));
    }

}
