<?php

namespace lightninghowl\reader;



//use lightninghowl\reader\JsonReader;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-28 at 09:30:11.
 */
class JsonReaderTest extends \PHPUnit_Framework_TestCase {

    /**
     * @covers lightninghowl\reader\JsonReader::get
     */
    public function testGetA() {
        $d = DIRECTORY_SEPARATOR;
        $rootDir = realpath(__DIR__ . $d . '..' . $d . '..' . $d . '..' . $d);
        $jsonPath = $rootDir . $d . 'files' . $d . 'test' . $d . 'test.json';

        $object = new JsonReader($jsonPath);
        $this->assertEquals(1, $object->get('status'));
        $this->assertEquals('test', $object->get('message'));
        $this->assertEquals(array('foo' => 'bar'), $object->get('content'));
    }

    public function testGetB() {
        $object = new JsonReader('');
        $this->assertEquals(null, $object->get());
        $this->assertEquals(null, $object->get('foo'));
        $this->assertEquals(null, $object->get('bar'));
    }

    
    public function testConstruct(){
        $reader = new JsonReader(__DIR__ . DIRECTORY_SEPARATOR . 'test.json');
        $this->assertEquals('bar', $reader->get('foo'));
    }
    
    public function testConstruct1(){
        $reader = new JsonReader('test.json');
        $this->assertEquals('bar', $reader->get('foo'));
        $this->assertEquals(null, $reader->get('bar'));
    }
}
