<?php

namespace househub\status\parsers;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-03 at 07:52:16.
 */
class JsonToStatusParserTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var JsonToStatusParser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new JsonToStatusParser();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers househub\status\parsers\JsonToStatusParser::parse
     * @todo   Implement testParse().
     */
    public function testParse() {
        $name = 'status';
        $value = 1;
        $status = new \househub\status\StatusStructure();
        $status->setName($name);
        $status->setValue($value);
        
        $getStatus = $this->object->parse($name, $value);
        $this->assertEquals($status, $getStatus);
    }

}
