<?php

namespace househub\status\parsers;

use ArrayObject;
use househub\json\JsonData;
use househub\json\JsonObject;
use househub\status\StatusStructure;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-03 at 07:54:53.
 */
class StatusStructureJsonParserTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var StatusStructureJsonParser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new StatusStructureJsonParser;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     *  househub\status\parsers\StatusStructureJsonParser::parse
     * @todo   Implement testParse().
     */
    public function testParse() {
        $status = new StatusStructure;
        $status->setId(1);
        $status->setName('status');
        $status->setValue(0);
        $status->setObjectId(1);
        
        $json = new JsonObject;
        $json->addElement(new JsonData("id", 1));
	$json->addElement(new JsonData("name", 'status'));
	$json->addElement(new JsonData("value", 0));
        
        $this->assertEquals($json, $this->object->parse($status));
    }
    
    public function testParse1() {
        $this->assertEquals(new JsonObject(), $this->object->parse(null));
    }
    
    public function testParse2() {
        $this->assertEquals(new JsonObject(), $this->object->parse(new ArrayObject()));
    }

}
