<?php

namespace househub\users\dao;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-03 at 02:12:48.
 */
class UserStructureDAOTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var UserStructureDAO
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new UserStructureDAO;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * househub\users\dao\UserStructureDAO::insert
     * @todo   Implement testInsert().
     */
    public function testInsert() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
