<?php

namespace househub\access\strategies\files;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-01 at 20:49:12.
 */
class ImageGatheringAccessStrategyTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ImageGatheringAccessStrategy
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ImageGatheringAccessStrategy;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo   Implement testRequestAccess().
     */
    public function testRequestAccess() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
