<?php

namespace househub\access\strategies\user;

$d = DIRECTORY_SEPARATOR;
require_once(realpath(__DIR__ . $d . ".." . $d . "session" .  $d . "LoginHelper.php"));

use househub\access\strategies\session\LoginHelper;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-03 at 01:09:33.
 */
class AddUserAccessStrategyTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var AddUserAccessStrategy
     */
    protected $object;
    private $loginHelper;
    /**
     * @group cookie
     */
    protected function setUp() {
        $this->object = new AddUserAccessStrategy;
        $this->loginHelper = new LoginHelper();
        $this->loginHelper->doLogin();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * househub\access\strategies\user\AddUserAccessStrategy::requestAccess
     * @group cookie
     */
    public function testRequestAccess() {
        // Remove the following lines when you implement this test.
        $parameters = array();
//        $parameters['']...
        $this->object->requestAccess($parameters);
    }

}
