<?php

namespace househub\services;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-03 at 14:28:04.
 */
class ServiceStructureTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ServiceStructure
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ServiceStructure;
        $this->object->setId(1);
        $this->object->setName('service');
        $this->object->setObjectId(2);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers househub\services\ServiceStructure::getId
     * @todo   Implement testGetId().
     */
    public function testGetId() {
        $this->assertEquals(1, $this->object->getId());
    }

    /**
     * @covers househub\services\ServiceStructure::getObjectId
     * @todo   Implement testGetObjectId().
     */
    public function testGetObjectId() {
        $this->assertEquals(2, $this->object->getObjectId());
    }

    /**
     * @covers househub\services\ServiceStructure::getName
     * @todo   Implement testGetName().
     */
    public function testGetName() {
        $this->assertEquals('service', $this->object->getName());
    }

    /**
     * @covers househub\services\ServiceStructure::setId
     * @todo   Implement testSetId().
     */
    public function testSetId() {
        $this->object->setId(2);
        $this->assertEquals(2, $this->object->getId());
    }

    /**
     * @covers househub\services\ServiceStructure::setObjectId
     * @todo   Implement testSetObjectId().
     */
    public function testSetObjectId() {
        $this->object->setObjectId(3);
        $this->assertEquals(3, $this->object->getObjectId());
    }

    /**
     * @covers househub\services\ServiceStructure::setName
     * @todo   Implement testSetName().
     */
    public function testSetName() {
        $this->object->setName('asdf');
        $this->assertEquals('asdf', $this->object->getName());
    }

}
