<?php

namespace househub\access\strategies\groups;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-03 at 01:38:39.
 */
class ListGroupsAccessStrategyTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ListGroupsAccessStrategy
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ListGroupsAccessStrategy;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers househub\access\strategies\groups\ListGroupsAccessStrategy::requestAccess
     * @todo   Implement testRequestAccess().
     */
    public function testRequestAccess() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
