<?php
namespace lightninghowl\utils\date;

require_once realpath(dirname(__FILE__).'\\..\\..\\..\\..\\lightninghowl\\utils').'\\AutoLoader.class.php';
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-28 at 09:57:15.
 */
class DMAFormatTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var DMYFormat
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $date = new Date('2000-01-02 12:30:00');
        $this->object = new DMYFormat($date);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers lightninghowl\utils\date\DMAFormat::getMask
     * @todo   Implement testGetMask().
     */
    public function testGetMask() {
        $this->assertEquals('02/01/2000 12:30:00', $this->object->getMask());
    }

}
