<?php

namespace lightninghowl\utils\date;

require_once dirname(__FILE__).'\\..\\..\\..\\..\\lightninghowl\\utils\\AutoLoader.class.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-28 at 10:18:37.
 */
class YMDFormatTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var YMDFormat
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $date = new Date('2000-01-02 11:12:13');
        $this->object = new YMDFormat($date);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers lightninghowl\utils\date\YMDFormat::getMask
     * @todo   Implement testGetMask().
     */
    public function testGetMask() {
        $this->assertEquals('2000/01/02 11:12:13', $this->object->getMask());
    }

}
