<?php

namespace lightninghowl\utils\encrypting;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-03 at 09:31:30.
 */
class Base64ReverseTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Base64Reverse
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Base64Reverse;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers lightninghowl\utils\encrypting\Base64Reverse::encrypt
     * @todo   Implement testEncrypt().
     */
    public function testEncrypt() {
        $this->assertEquals('=kFWOtmWtNWP', $this->object->encrypt('asdfg'));
    }

    /**
     * @covers lightninghowl\utils\encrypting\Base64Reverse::decrypt
     * @todo   Implement testDecrypt().
     */
    public function testDecrypt() {
        $this->assertEquals('asdfg', $this->object->decrypt('=kFWOtmWtNWP'));
    }

}
