<?php

namespace househub\services\parsers;

while(!file_exists(getcwd()."/.htroot")){chdir('..');}
require_once 'lightninghowl/utils/AutoLoader.class.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-03 at 14:33:14.
 */
class ServiceStructureJsonParserTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ServiceStructureJsonParser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ServiceStructureJsonParser;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    public function testParse() {
        $this->assertEquals(new \househub\json\JsonObject, $this->object->parse(null));
    }

    public function testParse1() {
        $this->assertEquals(new \househub\json\JsonObject, $this->object->parse(new \lightninghowl\utils\encrypting\Base64Reverse));
    }

    public function testParse2() {
        $entity = new \househub\services\ServiceStructure();
        $entity->setId(1);
        $entity->setName('service');
        
        $encoder = new \lightninghowl\utils\encrypting\Base64Reverse();
        $json = new \househub\json\JsonObject();
        $json->addElement(new \househub\json\JsonData("id", $encoder->encrypt($entity->getId())));
        $json->addElement(new \househub\json\JsonData("name", $entity->getName()));
        
        $this->assertEquals($json, $this->object->parse($entity));
    }

}
