<?php

namespace househub\objects\home;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-03 at 17:23:12.
 */
class HomeObjectManagerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var HomeObjectManager
     */
    protected $object;
    
    /**
     * @var PDO
     */
    protected $pdo;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new HomeObjectManager();
        $this->pdo = \househub\access\DatabaseConnector::getDriver();
        $this->pdo->beginTransaction();
    }
    
    protected function tearDown() {
        
        $this->pdo->rollBack();
    }

    

    /**
     *  househub\objects\home\HomeObjectManager::saveObject
     */
    public function testSaveObject() {
        $object = $this->makeObject();
    }
    
    /**
     * @return HomeObject
     */
    private function makeObject(){
        $object = new HomeObject();
        
    }
    
    /**
     *  househub\objects\home\HomeObjectManager::loadObject
     * @todo   Implement testLoadObject().
     */
    public function testLoadObject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     *  househub\objects\home\HomeObjectManaobjectger::loadStructure
     * @todo   Implement testLoadStructure().
     */
    public function testLoadStructure() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     *  househub\objects\home\HomeObjectManager::loadVisualName
     * @todo   Implement testLoadVisualName().
     */
    public function testLoadVisualName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     *  househub\objects\home\HomeObjectManager::loadVisualIconpack
     * @todo   Implement testLoadVisualIconpack().
     */
    public function testLoadVisualIconpack() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     *  househub\objects\home\HomeObjectManager::loadServices
     * @todo   Implement testLoadServices().
     */
    public function testLoadServices() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     *  househub\objects\home\HomeObjectManager::loadStatus
     * @todo   Implement testLoadStatus().
     */
    public function testLoadStatus() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     *  househub\objects\home\HomeObjectManager::loadSubObjects
     * @todo   Implement testLoadSubObjects().
     */
    public function testLoadSubObjects() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     *  househub\objects\home\HomeObjectManager::loadScheme
     * @todo   Implement testLoadScheme().
     */
    public function testLoadScheme() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
