<?php

namespace househub\answer;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-26 at 19:20:16.
 */
class AnswerEntityTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var AnswerEntity
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AnswerEntity;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers househub\answer\AnswerEntity::getStatus
     * @todo   Implement testGetStatus().
     */
    public function testGetStatus() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers househub\answer\AnswerEntity::getMessage
     * @todo   Implement testGetMessage().
     */
    public function testGetMessage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers househub\answer\AnswerEntity::getContent
     * @todo   Implement testGetContent().
     */
    public function testGetContent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers househub\answer\AnswerEntity::setStatus
     * @todo   Implement testSetStatus().
     */
    public function testSetStatus() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers househub\answer\AnswerEntity::setMessage
     * @todo   Implement testSetMessage().
     */
    public function testSetMessage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers househub\answer\AnswerEntity::setContent
     * @todo   Implement testSetContent().
     */
    public function testSetContent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers househub\answer\AnswerEntity::addContent
     * @todo   Implement testAddContent().
     */
    public function testAddContent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
