<?php

namespace househub\access\strategies\groups;

$d = DIRECTORY_SEPARATOR;
require_once (__DIR__ . $d . "..".$d . "ObjectMakerHelper.class.php");

use househub\access\DatabaseConnector;
use PDO;
use tests\househub\access\strategies\LoginHelper;
use tests\househub\access\strategies\ObjectMakerHelper;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-05 at 02:11:23.
 */
class AddGroupAccessStrategyTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var AddGroupAccessStrategy
     */
    protected $object;
     /** @var PDO
     */
    protected $pdo;
     /** @var LoginHelper
     */
    protected $loginHelper;

    protected function setUp() {
        $this->pdo = DatabaseConnector::getDriver();
        $this->pdo->beginTransaction();
        
        $this->object = new AddGroupAccessStrategy($this->pdo);
        $this->loginHelper = new LoginHelper();
    }
    
    protected function tearDown() {
        $this->pdo->rollBack();
    }

    /**
     * househub\access\strategies\groups\AddGroupAccessStrategy::requestAccess
     */
    public function testRequestAccess() {
        $objects = ObjectMakerHelper::makeManyObjects();
        $objParameters = array();
        
        foreach($objects as $obj){
            $insertedObj = (ObjectMakerHelper::insertNewObject($this->pdo, $obj));
            $objParameters[] = $insertedObj->getId();
        }
        $this->loginHelper->doLogin();
        $parameters = array(    
            AddGroupAccessStrategy::GROUP_NAME_ARG => "grupoName" ,
            AddGroupAccessStrategy::OBJECTS_ARG => $objParameters
        );
        
        $answer = $this->object->requestAccess($parameters);
        $this->assertEquals(1, $answer->getStatus());
    }

}
