<?php

namespace househub\access\strategies\groups;

use househub\access\DatabaseConnector;
use PDO;
use tests\househub\access\strategies\LoginHelper;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-03 at 01:38:39.
 */
class ListGroupsAccessStrategyTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ListGroupsAccessStrategy
     */
    protected $object;

     /** @var PDO
     */
    protected $pdo;

    /** @var LoginHelper
     */
    protected $loginHelper;

    protected function setUp() {
        $this->pdo = DatabaseConnector::getDriver();
        $this->pdo->beginTransaction();
        
        $this->object = new ListGroupsAccessStrategy;
        $this->loginHelper = new LoginHelper();
    }
    
    protected function tearDown() {
        $this->pdo->rollBack();
    }

    /**
     * househub\access\strategies\groups\ListGroupsAccessStrategy::requestAccess
     */
    public function testRequestAccess() {
        
    }

}
