<?php

namespace lightninghowl\database;

while(!file_exists(getcwd()."/.htroot")){chdir('..');}
require_once 'lightninghowl/utils/AutoLoader.class.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-28 at 07:31:28.
 */
class DbDriverTest extends \PHPUnit_Framework_TestCase {

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * 
     * @covers lightninghowl\database\DbDriver::__construct
     */
    public function testContruct(){
        
    }
    
    /**
     * @covers lightninghowl\database\DbDriver::open
     * @todo   Implement testOpen().
     */
    public function testOpen() {
        $argument = new arguments\MySQLArgument();
        $argument->setDbName('househubtest');
        $argument->setDbUser('app');
        $argument->setDbPass('123456abc');
        $argument->setHost('localhost');
        $argument->setPort(3306);
        
        $pdo = DbDriver::open($argument);
        $this->assertTrue(true);
    }

}
