<?php

namespace househub\access\strategies\session;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-02 at 02:25:50.
 */
class LogoutAccessStrategyTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var LogoutAccessStrategy
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new LogoutAccessStrategy;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers househub\access\strategies\session\LogoutAccessStrategy::requestAccess
     * @todo   Implement testRequestAccess().
     */
    public function testRequestAccess() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
