<?php

namespace househub\access\strategies\session;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-02 at 02:26:23.
 */
class VerifyLoginAccessStrategyTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var VerifyLoginAccessStrategy
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new VerifyLoginAccessStrategy;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @group cookie
     */
    public function testRequestAccess() {
        //Fazer login
        $parameters = array(
            "method" => "login",
            "username" => "adm",
            "password" => "123456"
        );
        $loginAccess = new LoginAccessStrategy();
        $loginAccess->requestAccess($parameters); 
        
        $answer = $this->object->requestAccess(array("method"=>"verify_login"));
        $this->assertEquals(1,$answer->getStatus());
    }
    /**
     * @group cookie
     */
    public function testVerifyLoginFail() {
        // Remove the following lines when you implement this test.
        $answer = $this->object->requestAccess(array("method"=>"verify_login"));
        $this->assertEquals(0,$answer->getStatus());
    }

}
