<?php

namespace househub\json;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-03 at 12:10:52.
 */
class JsonDataTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var JsonData
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new JsonData("nome", null);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     *  househub\json\JsonData::getValue
     */
    public function testGetValue() {
        $this->assertNull($this->object->getValue());
    }

    /**
     *  househub\json\JsonData::setValue
     */
    public function testSetValue() {
        $this->object->setValue(1);
        $this->assertEquals(1, $this->object->getValue());
        
        return $this->object;
    }

    /**
     *  househub\json\JsonData::valueToString
     * @dataProvider provider
     */
    public function testValueToString($jsonData, $expected) {
        $this->assertEquals($expected, $jsonData->valueToString());
    }
    
    public function provider(){
        return array(
            array(new JsonData("nome", NULL), 'null'),
            array(new JsonData("nome", 1), '1'),
            array(new JsonData("nome", 0), '0'),
            array(new JsonData("nome", "string"), '"string"'),
            array(new JsonData("nome", true), 'true'),
            array(new JsonData("nome", false), 'false')
        );
    }

}
