<?php

namespace househub\status\builders;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-03 at 08:02:30.
 */
class StatusStructureBuilderTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var StatusStructureBuilder
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new StatusStructureBuilder;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers househub\status\builders\StatusStructureBuilder::build
     * @todo   Implement testBuild().
     */
    public function testBuild() {
        $resource = array(
            \househub\status\tables\StatusStructureTable::COLUMN_ID => 1,
            \househub\status\tables\StatusStructureTable::COLUMN_NAME => 'status',
            \househub\status\tables\StatusStructureTable::COLUMN_OBJECT_ID => 1,
            \househub\status\tables\StatusStructureTable::COLUMN_VALUE => 3
        );
        
        $expectedStatus = new \househub\status\StatusStructure();
        $expectedStatus->setId(1);
        $expectedStatus->setName('status');
        $expectedStatus->setObjectId(1);
        $expectedStatus->setValue(3);
        
        $this->assertEquals($expectedStatus, $this->object->build($resource));
    }

}
