<?php

namespace househub\users\authentication;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-04 at 02:38:34.
 */
class PasswordAuthenticationTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var PasswordAuthentication
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PasswordAuthentication;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    public function testGetUser(){
        $this->assertNull($this->object->getUser());
    }
    
    public function testGetPassword(){
        $this->assertNull($this->object->getPassword());
    }
    
    public function testSetParameters() {
        $parameters = array('user' => 'adm', 'password' => '123456');
        $this->object->setParameters($parameters);
        $this->assertEquals('adm', $this->object->getUser());
        $this->assertEquals('123456', $this->object->getPassword());
    }

    public function testAuthenticate() {
        $driver = \househub\access\DatabaseConnector::getDriver();
        $parameters = array('user' => 'adm', 'password' => '123456');
        $this->object->setParameters($parameters);
        $user = $this->object->authenticate($driver);
        
        $this->assertNotNull($user);
    }

}
