<?php

namespace househub\access\strategies\object;

use househub\access\DatabaseConnector;
use househub\answer\JsonAnswerParser;
use househub\objects\home\HomeObject;
use househub\objects\home\HomeObjectManager;
use househub\objects\ObjectStructure;
use PDO;
use tests\househub\access\strategies\LoginHelper;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-04 at 23:56:16.
 */
class ListObjectsAccessStrategyTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ListObjectsAccessStrategy
     */
    protected $object;

     /** @var PDO
     */
    protected $pdo;
     /** @var LoginHelper
     */
    protected $loginHelper;

    protected function setUp() {
        $this->pdo = DatabaseConnector::getDriver();
        $this->pdo->beginTransaction();
        
        $this->object = new ListObjectsAccessStrategy($this->pdo);
        $this->loginHelper = new LoginHelper();
    }
    
    protected function tearDown() {
        $this->pdo->rollBack();
    }

    /**
     * househub\access\strategies\object\ListObjectsAccessStrategy::requestAccess
     * @group cookie
     */
    public function testRequestAccess() {
        $this->loginHelper->doLogin();
        $homeObject = $this->insertNewObject();
        $answer = $this->object->requestAccess(
                array()
        );
        
        $this->assertEquals(1, $answer->getStatus());
        $this->assertEquals("@success", $answer->getMessage());
        $this->assertNotNull($answer->getContent());
        
        
        $parser = new JsonAnswerParser();
        $json = $parser->answerToJson($answer);
        echo $json->toString() . "\n";
        echo $answer->getContent()->toString() . "\n";
        echo get_class($answer->getContent()) . "\n";
                
    }

    public function insertNewObject(){
        $homeObject = $this->makeObject();
        $homeManager = new HomeObjectManager();
        $homeManager->saveObject($homeObject, $this->pdo);
        return $homeObject;
    }
    
    public function makeObject(){
        $homeObj = new HomeObject();
        $homeObj->setStructure($this->makeStructure());
        return $homeObj;
    }
    
    /**
     * @return ObjectStructure
     */
    private function makeStructure(){
        $structure = new ObjectStructure();
        $structure->setAddress("http://192.168.0.100");
        $structure->setSchemeName("basicDoor");
        $structure->setConnected(false);
        $structure->setType("door");
        
        return $structure;
    }
}
