<?php

namespace househub\services\parsers;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-03 at 14:30:27.
 */
class JsonToServiceParserTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var JsonToServiceParser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new JsonToServiceParser;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers househub\services\parsers\JsonToServiceParser::parse
     * @todo   Implement testParse().
     */
    public function testParse() {
        $service = new \househub\services\ServiceStructure;
        $service->setName('service');
        
        $this->assertEquals($service, $this->object->parse('service'));
    }

}
