<?php

namespace lightninghowl\utils\url;

require_once realpath(dirname(__FILE__) . '/../../../../lightninghowl/utils/AutoLoader.class.php');
//$d = DIRECTORY_SEPARATOR;
//require_once dirname(__FILE__).$d . '..' . $d . '..' . $d . '..' . $d . 'lightninghowl'. $d .'utils' . $d . 'AutoLoader.class.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-28 at 10:27:05.
 */
class UrlHandlerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var UrlHandler
     */
    protected $handler;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->handler = new UrlHandler('http://localhost', 'GET');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * lightninghowl\utils\url\UrlHandler::setTimeout
     * @todo   Implement testSetTimeout().
     */
    public function testSetTimeout() {
        $this->object->setTimeout(30);
        $this->assertEquals(30, $this->object->getTimeout());
    }

    /**
     * lightninghowl\utils\url\UrlHandler::getTimeout
     * @todo   Implement testGetTimeout().
     */
    public function testGetTimeout() {
        $this->object->setTimeout(30);
        $this->assertEquals(30, $this->object->getTimeout());
    }

    /**
     * lightninghowl\utils\url\UrlHandler::getContent
     * @todo   Implement testGetContent().
     */
    public function testGetContent() {
        $this->assertEquals(null, $this->handler->getContent());
        $this->handler->run();
        $this->assertNotNull($this->handler->getContent());
    }

    /**
     * lightninghowl\utils\url\UrlHandler::getHeader
     * @todo   Implement testGetHeader().
     */
    public function testGetHeader() {
        $this->handler->run();
        $this->assertNotNull($this->handler->getHeader());
    }

    /**
     * lightninghowl\utils\url\UrlHandler::getStatus
     * @todo   Implement testGetStatus().
     */
    public function testGetStatus() {
        $this->handler->run();
        $this->assertNotNull($this->handler->getStatus());
        $this->assertTrue($this->handler->getStatus()!=0);
    }

    /**
     * lightninghowl\utils\url\UrlHandler::addField
     * @todo   Implement testAddField().
     */
    public function testAddField() {
        $this->handler->addField('foo', 'bar');
        $url = $this->handler->run();
        $this->assertEquals('http://localhost?foo=bar', $url);
    }

    /**
     * lightninghowl\utils\url\UrlHandler::run
     * @todo   Implement testRun().
     */
    public function testRun() {
        $handler = new UrlHandler('http://localhost', 'GET');
        $this->assertEquals(null, $handler->getContent());
        $this->assertEquals(null, $handler->getStatus());
        $handler->run();
        $this->assertTrue(!is_null($handler->getContent()));
        $this->assertTrue(!is_null($handler->getStatus()));
        
        $handler = new UrlHandler('http://localhost', 'POST');
        $this->assertEquals(null, $handler->getContent());
        $this->assertEquals(null, $handler->getStatus());
        $handler->run();
        $this->assertTrue(!is_null($handler->getContent()));
        $this->assertTrue(!is_null($handler->getStatus()));
    }

}
