<?php

namespace lightninghowl\utils\url;

require_once realpath(dirname(__FILE__).'/../../../../lightninghowl/utils/AutoLoader.class.php');
//$d = DIRECTORY_SEPARATOR;
//require_once dirname(__FILE__).$d . '..' . $d . '..' . $d . '..' . $d . 'lightninghowl'. $d .'utils' . $d . 'AutoLoader.class.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-28 at 10:27:05.
 */
class UrlHandlerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var UrlHandler
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new UrlHandler('http://www.google.com.br', 'GET');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers lightninghowl\utils\url\UrlHandler::setTimeout
     * @todo   Implement testSetTimeout().
     */
    public function testSetTimeout() {
        $this->assertTrue(true);
    }

    /**
     * @covers lightninghowl\utils\url\UrlHandler::getTimeout
     * @todo   Implement testGetTimeout().
     */
    public function testGetTimeout() {
        $this->assertTrue(true);
    }

    /**
     * @covers lightninghowl\utils\url\UrlHandler::getContent
     * @todo   Implement testGetContent().
     */
    public function testGetContent() {
        $this->assertEquals(null, $this->object->getContent());
        $this->object->run();
        $this->assertEquals('200', $this->object->getStatus());
    }

    /**
     * @covers lightninghowl\utils\url\UrlHandler::getHeader
     * @todo   Implement testGetHeader().
     */
    public function testGetHeader() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers lightninghowl\utils\url\UrlHandler::getStatus
     * @todo   Implement testGetStatus().
     */
    public function testGetStatus() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers lightninghowl\utils\url\UrlHandler::addField
     * @todo   Implement testAddField().
     */
    public function testAddField() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers lightninghowl\utils\url\UrlHandler::run
     * @todo   Implement testRun().
     */
    public function testRun() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
