<?php

namespace househub\users\dao;

use househub\access\DatabaseConnector;
use househub\users\UserStructure;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-03 at 02:12:48.
 */
class UserStructureDAOTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var UserStructureDAO
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
//        $this->object = new UserStructureDAO;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    public function testInsert() {
        $driver = DatabaseConnector::getDriver();
        $user = new UserStructure();
        $user->setName('test');
    }

}
