<?php

namespace househub\intents\home;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-03 at 10:35:17.
 */
class HomeIntentManagerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var HomeIntentManager
     */
    protected $object;
    
    /**
     * @var PDO
     */
    protected $pdo;
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new HomeIntentManager;
        $this->pdo = \househub\access\DatabaseConnector::getDriver();
        $this->pdo->beginTransaction();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
        $this->pdo->rollBack();
    }

    /**
     *  househub\intents\home\HomeIntentManager::loadIntent
     * @todo   Implement testLoadIntent().
     */
    public function testLoadIntent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     *  househub\intents\home\HomeIntentManager::loadStructure
     * @todo   Implement testLoadStructure().
     */
    public function testLoadStructure() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     *  househub\intents\home\HomeIntentManager::loadSubIntents
     */
    public function testLoadSubIntents() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     *  househub\intents\home\HomeIntentManager::saveIntent
     * @todo   Implement testSaveIntent().
     */
    public function testSaveIntent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     *  househub\intents\home\HomeIntentManager::deleteIntent
     * @todo   Implement testDeleteIntent().
     */
    public function testDeleteIntent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
