<?php

namespace lightninghowl\utils;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-01 at 13:48:17.
 */
class StrOpersTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var StrOpers
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new StrOpers;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * lightninghowl\utils\StrOpers::strEndsWith
     * @todo   Implement testStrEndsWith().
     */
    public function testStrEndsWith() {
        $this->assertTrue(StrOpers::strEndsWith('stringtest', 'test'));
    }

    /**
     * lightninghowl\utils\StrOpers::strStartsWith
     * @todo   Implement testStrStartsWith().
     */
    public function testStrStartsWith() {
        $this->assertTrue(StrOpers::strStartsWith('stringtest', 'string'));
    }

    /**
     * lightninghowl\utils\StrOpers::strFixPath
     * @todo   Implement testStrFixPath().
     */
    public function testStrFixPath() {
        $this->assertEquals('C:' . DIRECTORY_SEPARATOR . 'test', StrOpers::strFixPath('C:/test'));
    }

    /**
     * lightninghowl\utils\StrOpers::strWebPath
     * @todo   Implement testStrWebPath().
     */
    public function testStrWebPath() {
        $this->assertEquals('localhost/home', StrOpers::strWebPath('localhost/home'));
    }

    public function testVarFancyDump(){
        $var = array('foo' => 'bar');
        StrOpers::varFancyDump($var);
        $this->assertTrue(true);
    }
    
}
