<?php

namespace lightninghowl\utils;

require_once dirname(__FILE__).'\\..\\..\\..\\lightninghowl\\utils\\AutoLoader.class.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-28 at 10:34:08.
 */
class StrOpersTest extends \PHPUnit_Framework_TestCase {

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers lightninghowl\utils\StrOpers::varFancyDump
     * @todo   Implement testVarFancyDump().
     */
    public function testVarFancyDump() {
        $this->assertTrue(true);
    }

    /**
     * @covers lightninghowl\utils\StrOpers::strEndsWith
     * @todo   Implement testStrEndsWith().
     */
    public function testStrEndsWith() {
        $this->assertTrue(StrOpers::strEndsWith('stringtest', 'test'));
    }

    /**
     * @covers lightninghowl\utils\StrOpers::strStartsWith
     * @todo   Implement testStrStartsWith().
     */
    public function testStrStartsWith() {
        $this->assertTrue(StrOpers::strStartsWith('stringtest', 'string'));
    }

    /**
     * @covers lightninghowl\utils\StrOpers::strFixPath
     * @todo   Implement testStrFixPath().
     */
    public function testStrFixPath() {
        $this->assertEquals('C:\\test', StrOpers::strFixPath('C:/test'));
    }

    /**
     * @covers lightninghowl\utils\StrOpers::strWebPath
     * @todo   Implement testStrWebPath().
     */
    public function testStrWebPath() {
        $this->assertEquals('localhost/home', StrOpers::strWebPath('localhost/home'));
    }

}
