<?php

namespace househub\scheme;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-03 at 00:09:55.
 */
class SchemeTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Scheme
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Scheme;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * househub\scheme\Scheme::getSchemeName
     * @todo   Implement testGetSchemeName().
     */
    public function testGetSchemeName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * househub\scheme\Scheme::getSchemeVersion
     * @todo   Implement testGetSchemeVersion().
     */
    public function testGetSchemeVersion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * househub\scheme\Scheme::getObjectType
     * @todo   Implement testGetObjectType().
     */
    public function testGetObjectType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * househub\scheme\Scheme::getConfigs
     * @todo   Implement testGetConfigs().
     */
    public function testGetConfigs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * househub\scheme\Scheme::getStatus
     * @todo   Implement testGetStatus().
     */
    public function testGetStatus() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * househub\scheme\Scheme::getServices
     * @todo   Implement testGetServices().
     */
    public function testGetServices() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * househub\scheme\Scheme::getConditions
     * @todo   Implement testGetConditions().
     */
    public function testGetConditions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * househub\scheme\Scheme::setSchemeName
     * @todo   Implement testSetSchemeName().
     */
    public function testSetSchemeName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * househub\scheme\Scheme::setSchemeVersion
     * @todo   Implement testSetSchemeVersion().
     */
    public function testSetSchemeVersion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * househub\scheme\Scheme::setObjectType
     * @todo   Implement testSetObjectType().
     */
    public function testSetObjectType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * househub\scheme\Scheme::setConfigs
     * @todo   Implement testSetConfigs().
     */
    public function testSetConfigs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * househub\scheme\Scheme::setStatus
     * @todo   Implement testSetStatus().
     */
    public function testSetStatus() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * househub\scheme\Scheme::setServices
     * @todo   Implement testSetServices().
     */
    public function testSetServices() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * househub\scheme\Scheme::setConditions
     * @todo   Implement testSetConditions().
     */
    public function testSetConditions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
