<?php

namespace househub\readers;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-03 at 08:27:26.
 */
class DictionaryTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Dictionary
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Dictionary;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers househub\readers\Dictionary::setSource
     * @todo   Implement testSetSource().
     */
    public function testSetSource() {
        $this->object->setSource(array('item' => 'x'));
    }

    /**
     * @covers househub\readers\Dictionary::translate
     * @todo   Implement testTranslate().
     */
    public function testTranslate() {
        $this->object->setSource(array('item' => 'x'));
        $this->assertEquals('x', $this->object->translate('item'));
        $this->assertEquals('none', $this->object->translate('none'));
    }

}
