<?php

namespace househub\readers;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-03 at 08:33:00.
 */
class LanguageReaderTest extends \PHPUnit_Framework_TestCase {

    public function testGetInstance() {
        $this->assertTrue(LanguageReader::getInstance() instanceof LanguageReader);
    }

}
