<?php

namespace househub\groups;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-05 at 01:13:39.
 */
class GroupStructureTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var GroupStructure
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new GroupStructure;
        $this->object->setId(1);
        $this->object->setUserId(2);
        $this->object->setRegistrationDate('12-12-2012 00:00:00');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers househub\groups\GroupStructure::getId
     * @todo   Implement testGetId().
     */
    public function testGetId() {
        $this->assertEquals(1, $this->object->getId());
    }

    /**
     * @covers househub\groups\GroupStructure::getUserId
     * @todo   Implement testGetUserId().
     */
    public function testGetUserId() {
        $this->assertEquals(2, $this->object->getUserId());
    }

    /**
     * @covers househub\groups\GroupStructure::getRegistrationDate
     * @todo   Implement testGetRegistrationDate().
     */
    public function testGetRegistrationDate() {
        $this->assertEquals('12-12-2012 00:00:00', $this->object->getRegistrationDate());
    }

    /**
     * @covers househub\groups\GroupStructure::setId
     * @todo   Implement testSetId().
     */
    public function testSetId() {
        $this->object->setId(2);
        $this->assertEquals(2, $this->object->getId());
    }

    /**
     * @covers househub\groups\GroupStructure::setUserId
     * @todo   Implement testSetUserId().
     */
    public function testSetUserId() {
        $this->object->setUserId(1);
        $this->assertEquals(1, $this->object->getUserId());
    }

    /**
     * @covers househub\groups\GroupStructure::setRegistrationDate
     * @todo   Implement testSetRegistrationDate().
     */
    public function testSetRegistrationDate() {
        $this->object->setRegistrationDate('01-01-2010 01:01:01');
        $this->assertEquals('01-01-2010 01:01:01', $this->object->getRegistrationDate());
    }

}
