<?php

namespace househub\conditions;

/**
<<<<<<< HEAD
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-03 at 13:51:29.
=======
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-03 at 14:50:01.
>>>>>>> 98e764939e22b5fd80227ac3d9e274b04d69cab9
 */
class ObjectConditionTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ObjectCondition
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ObjectCondition("nome");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

//    /**
//     *  househub\conditions\ObjectCondition::getName
//     * @todo   Implement testGetName().
//     */
//    public function testGetName() {
//        $this->assertEquals('condition', $this->object->getName());
//    }

    /**
     *  househub\conditions\ObjectCondition::setName
     * @todo   Implement testSetName().
     */
    public function testSetName() {
        $this->object->setName('name');
        $this->assertEquals('name', $this->object->getName());
    }

    /**
     *  househub\conditions\ObjectCondition::addRestriction
     * @todo   Implement testAddRestriction().
     */
    public function testAddRestriction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     *  househub\conditions\ObjectCondition::getRestriction
     * @todo   Implement testGetRestriction().
     */
    public function testGetRestriction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     *  househub\conditions\ObjectCondition::removeRestriction
     * @todo   Implement testRemoveRestriction().
     */
    public function testRemoveRestriction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     *  househub\conditions\ObjectCondition::isValid
     * @todo   Implement testIsValid().
     */
    public function testIsValid() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
