<?php

namespace lightninghowl\utils\sql;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-03 at 06:44:24.
 */
class DeleteQueryTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var DeleteQuery
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new DeleteQuery;
        $this->object->setEntity('table');
        $criteria = new SqlCriteria();
        $criteria->add(new SqlFilter('column', '=', 1));
        $this->object->setCriteria($criteria);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers lightninghowl\utils\sql\DeleteQuery::getInstruction
     * @todo   Implement testGetInstruction().
     */
    public function testGetInstruction() {
        $this->assertEquals('DELETE FROM table WHERE (column = 1)', $this->object->getInstruction());
    }

}
