<?php

namespace lightninghowl\utils\sql;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-03 at 06:57:13.
 */
class EntityFilterTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var EntityFilter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new EntityFilter('column', '=', 'column');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        $this->assertEquals("column = column", $this->object->dump());
    }

    /**
     * @covers lightninghowl\utils\sql\EntityFilter::dump
     * @todo   Implement testDump().
     */
    public function testDump() {
        
    }

}
