<?php

namespace lightninghowl\utils\sql;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-03 at 07:00:16.
 */
class InnerJoinTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var InnerJoin
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new InnerJoin;
        $this->object->setEntity('table t');
        $criteria = new SqlCriteria();
        $criteria->add(new EntityFilter('t.id', '=', 1));
        $this->object->setCriteria($criteria);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers lightninghowl\utils\sql\InnerJoin::dump
     * @todo   Implement testDump().
     */
    public function testDump() {
        $this->assertEquals('INNER JOIN table t ON (t.id = 1)', $this->object->dump());
    }

    public function testGetEntity(){
        $this->assertEquals('table t', $this->object->getEntity());
    }
    
    public function testGetCriteria(){
        $criteria = new SqlCriteria();
        $criteria->add(new EntityFilter('t.id', '=', 1));
        
        $this->assertEquals($criteria, $this->object->getCriteria());
    }
}
