<?php

namespace lightninghowl\utils\sql;

use Exception;

while(!file_exists(getcwd()."/.htroot")){chdir('..');}
require_once 'lightninghowl/utils/AutoLoader.class.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-03 at 07:04:15.
 */
class InsertQueryTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var InsertQuery
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new InsertQuery;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers lightninghowl\utils\sql\InsertQuery::setRowData
     * @todo   Implement testSetRowData().
     */
    public function testSetRowData() {
        $object = new InsertQuery();
        $object->setEntity('table');
        $object->setRowData('column', 'value');
        $this->assertEquals("INSERT INTO table (column)VALUES ('value')", $object->getInstruction());
    }

    /**
     * @covers lightninghowl\utils\sql\InsertQuery::setCriteria
     * @todo   Implement testSetCriteria().
     */
    public function testSetCriteria() {
        $object = new InsertQuery();
        $object->setEntity('table');
        $object->setRowData('column', 'value');
        $criteria = new SqlCriteria();
        try{
            $object->setCriteria($criteria);
            $this->assertTrue(false);
        }catch(Exception $e){
            echo $e->getMessage();
            $this->assertTrue(true);
        }
    }

    /**
     * @covers lightninghowl\utils\sql\InsertQuery::getInstruction
     * @todo   Implement testGetInstruction().
     */
    public function testGetInstruction() {
        $object = new InsertQuery();
        $object->setEntity('table');
        $object->setRowData('column', 'value');
        $this->assertEquals("INSERT INTO table (column)VALUES ('value')", $object->getInstruction());
    }

}
