<?php

namespace lightninghowl\utils\sql;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-03 at 09:37:29.
 */
class JoinTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Join
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers lightninghowl\utils\sql\Join::setEntity
     * @todo   Implement testSetEntity().
     */
    public function testSetEntity() {
        // Remove the following lines when you implement this test.
        
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers lightninghowl\utils\sql\Join::getEntity
     * @todo   Implement testGetEntity().
     */
    public function testGetEntity() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers lightninghowl\utils\sql\Join::setCriteria
     * @todo   Implement testSetCriteria().
     */
    public function testSetCriteria() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers lightninghowl\utils\sql\Join::getCriteria
     * @todo   Implement testGetCriteria().
     */
    public function testGetCriteria() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
