<?php

namespace lightninghowl\utils\sql;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-03 at 07:24:04.
 */
class SelectQueryTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var SelectQuery
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SelectQuery();
        $this->object->setEntity('table t');
        $this->object->addColumn('column');
        $criteria = new SqlCriteria();
        $criteria->add(new SqlFilter('t.id', '=', 5));
        $criteria->setBlockStatus('order', 't.id');
        $criteria->setBlockStatus('limit', 1);
        $criteria->setBlockStatus('offset', 1);
        $this->object->setCriteria($criteria);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers lightninghowl\utils\sql\SelectQuery::addColumn
     * @todo   Implement testAddColumn().
     */
    public function testAddColumn() {
        $this->object = new SelectQuery();
        $this->object->setEntity('table t');
        $this->object->addColumn('column');
        $criteria = new SqlCriteria();
        $criteria->add(new SqlFilter('t.id', '=', 5));
        $criteria->setBlockStatus('order', 't.id');
        $criteria->setBlockStatus('limit', 1);
        $criteria->setBlockStatus('offset', 1);
        $this->object->setCriteria($criteria);
        $this->object->addColumn('test');
        $this->assertEquals('SELECT column,test FROM table t WHERE (t.id = 5) ORDER BY t.id LIMIT 1 OFFSET 1', $this->object->getInstruction());
    }

    /**
     * @covers lightninghowl\utils\sql\SelectQuery::addJoin
     * @covers lightninghowl\utils\sql\SelectQuery::addColumn
     */
    public function testAddJoin() {
        
        $join = new InnerJoin();
        $join->setEntity('entity e');
        $criteria = new SqlCriteria();
        $criteria->add(new EntityFilter('t.id', '=', 'e.id'));
        $join->setCriteria($criteria);
        $this->object->addJoin($join);
        $expect = 'SELECT column FROM table t INNER JOIN entity e ON (t.id = e.id) WHERE (t.id = 5) ORDER BY t.id LIMIT 1 OFFSET 1';
        $this->assertEquals($expect, $this->object->getInstruction());
    }

    /**
     * @covers lightninghowl\utils\sql\SelectQuery::getInstruction
     * @todo   Implement testGetInstruction().
     */
    public function testGetInstruction() {
        $this->assertEquals('SELECT column FROM table t WHERE (t.id = 5) ORDER BY t.id LIMIT 1 OFFSET 1', $this->object->getInstruction());
    }

}
