<?php

namespace lightninghowl\utils\sql;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-03 at 07:39:05.
 */
class SqlFilterTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var SqlFilter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SqlFilter('column', '=', 2);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers lightninghowl\utils\sql\SqlFilter::dump
     * @todo   Implement testDump().
     */
    public function testDump() {
        $this->assertEquals('column = 2', $this->object->dump());
    }

}
