<?php

namespace lightninghowl\utils\sql;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-03 at 07:40:21.
 */
class UpdateQueryTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var UpdateQuery
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new UpdateQuery;
        $this->object->setEntity('table');
        $criteria = new SqlCriteria();
        $criteria->add(new SqlFilter('column', '=', 1));
        $this->object->setCriteria($criteria);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers lightninghowl\utils\sql\UpdateQuery::setRowData
     * @todo   Implement testSetRowData().
     */
    public function testSetRowData() {
        $this->object->setRowData('column', 'value');
        $this->assertEquals('UPDATE table SET column = \'value\' WHERE (column = 1)', $this->object->getInstruction());
    }

    /**
     * @covers lightninghowl\utils\sql\UpdateQuery::getInstruction
     * @todo   Implement testGetInstruction().
     */
    public function testGetInstruction() {
        $this->object->setRowData('column', 'value');
        $this->assertEquals('UPDATE table SET column = \'value\' WHERE (column = 1)', $this->object->getInstruction());
    }

}
